import rerun as rr
import rerun.blueprint as rrb
import numpy as np


# set rerun blueprint
def setup_rerun_blueprint():
    blueprint = rrb.Horizontal(
        rrb.Vertical(
            # 3D 뷰를 탭으로 분리: All / Points
            rrb.Tabs(
                rrb.Spatial3DView(
                    name="3D (All)",
                    origin="world",
                    #contents= "world",
                ),
            ),
            rrb.TextDocumentView(
                name="Description", 
                origin="/description"
                ),
            row_shares=[7, 3],
        ),
        rrb.Vertical(
            rrb.Spatial2DView(
                name="RGB",
                origin="world/camera/image",
                contents="world/camera/image/rgb",
            ),
            rrb.Tabs(
                rrb.Spatial2DView(
                    name="Depth (Foundation)",
                    origin="world/camera/image",
                    contents="world/camera/image/depth_foundation",
                ),
                rrb.Spatial2DView(
                    name="Depth (ZED)",
                    origin="world/camera/image",
                    contents="world/camera/image/depth_zed",
                ),
            ),
            rrb.Tabs(
                rrb.Spatial2DView(
                    name="Depth Map (Foundation)",
                    origin="image",
                    contents="image/depthmap_foundation",
                ),
                rrb.Spatial2DView(
                    name="Depth Map (ZED)",
                    origin="image",
                    contents="image/depthmap_zed",
                ),
            ),
            name="2D Views",
            row_shares=[3, 3, 3],
        ),
        column_shares=[3, 1],
    )
    rr.send_blueprint(blueprint)
    rr.log("world", rr.ViewCoordinates.RDF, static=True)
    # R: Right, D: Down, F: Forward / [meter]
   

# log description to rerun
def log_description():
    description = """
    ### ZED ROS Bag Visualizer

    This viewer displays the pre-processed output from the `preprocess_edit.py` script.

    - **3D View**:
      - Shows the camera's trajectory.
      - Displays up to two types of point clouds:
        - **Depth-based Point Cloud**: Automatically generated by Rerun. Can be toggled via `world/camera/image/depth_foundation` or `world/camera/image/depth_zed` in the tree view.
        - **Topic-based Point Cloud**: Loaded from `pointcloud.json`. Can be toggled via `world/camera/pointcloud_topic`.

    - **2D Views**:
      - **RGB**: The main RGB video feed.
      - **Depthmap**: A colorized representation of the depth video for visualization.
    """
    rr.log("description", rr.TextDocument(description, media_type=rr.MediaType.MARKDOWN), static=True)
